import {
  User,
  Agent,
  Conversation,
  Message,
  Notification,
  Favorite,
  CapabilityPackage,
} from './types';

export const getExpToNextLevel = (level: number): number => {
  return Math.floor(100 * Math.pow(1.5, level - 1));
};

export const mockUser: User = {
  id: 'user-1',
  name: 'OpenElf 用户',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=openelf',
  role: 'user',
  email: 'user@openelf.com',
  createdAt: new Date('2024-01-01').toISOString(),
  verificationStatus: 'unverified',
};

export const mockCreator: User = {
  id: 'user-2',
  name: '创作者小王',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=xiaowang',
  role: 'creator',
  email: 'creator@openelf.com',
  createdAt: new Date('2024-01-05').toISOString(),
  verificationStatus: 'verified',
  verificationPlatform: '小红书',
  verificationFollowers: 15000,
};

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    name: 'OpenElf',
    description: '全能 AI 助手，可以帮你写作、编程、分析数据',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=openelf',
    prompt: '你是一个友好的 AI 助手，叫 OpenElf。',
    category: '通用',
    creatorId: 'system',
    creatorName: '官方',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=system',
    isPublic: true,
    isFeatured: true,
    conversationCount: 12543,
    likes: 3421,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
    price: 19.9,
    totalSupply: 500,
    soldCount: 324,
    isListed: true,
    status: 'listed',
    level: 1,
    fans: 0,
    exp: 0,
    expToNextLevel: getExpToNextLevel(1),
    isShowcased: false,
  },
  {
    id: 'agent-2',
    name: '家庭医生',
    description: '提供专业的健康咨询和医疗建议',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=doctor',
    prompt: '你是一位专业的家庭医生。',
    category: '健康',
    creatorId: 'system',
    creatorName: '官方',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=system',
    isPublic: true,
    isFeatured: true,
    conversationCount: 8932,
    likes: 2156,
    createdAt: new Date('2024-01-02').toISOString(),
    updatedAt: new Date('2024-01-02').toISOString(),
    price: 29.9,
    totalSupply: 300,
    soldCount: 198,
    isListed: true,
    status: 'listed',
    level: 1,
    fans: 0,
    exp: 0,
    expToNextLevel: getExpToNextLevel(1),
    isShowcased: false,
  },
  {
    id: 'agent-3',
    name: '英语外教 Owen',
    description: '专业的英语口语陪练和语法老师',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=owen',
    prompt: 'You are Owen, an English teacher from the US.',
    category: '教育',
    creatorId: 'system',
    creatorName: '官方',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=system',
    isPublic: true,
    isFeatured: true,
    conversationCount: 5621,
    likes: 1832,
    createdAt: new Date('2024-01-03').toISOString(),
    updatedAt: new Date('2024-01-03').toISOString(),
    price: 39.9,
    totalSupply: 200,
    soldCount: 156,
    isListed: true,
    status: 'listed',
    level: 1,
    fans: 0,
    exp: 0,
    expToNextLevel: getExpToNextLevel(1),
    isShowcased: false,
  },
  {
    id: 'agent-4',
    name: '代码大师',
    description: '帮助你解决编程问题，写出高质量代码',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=coder',
    prompt: '你是一位资深程序员，精通多种编程语言。',
    category: '编程',
    creatorId: 'user-2',
    creatorName: '创作者小王',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=xiaowang',
    isPublic: true,
    isFeatured: false,
    conversationCount: 3210,
    likes: 987,
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
    price: 49.9,
    totalSupply: 100,
    soldCount: 87,
    isListed: true,
    status: 'listed',
    level: 1,
    fans: 0,
    exp: 0,
    expToNextLevel: getExpToNextLevel(1),
    isShowcased: false,
  },
  {
    id: 'agent-5',
    name: '文案策划',
    description: '帮你写出吸引人的文案和广告语',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=copywriter',
    prompt: '你是一位资深文案策划师。',
    category: '写作',
    creatorId: 'user-3',
    creatorName: '创意达人',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=creative',
    isPublic: true,
    isFeatured: false,
    conversationCount: 2856,
    likes: 756,
    createdAt: new Date('2024-01-12').toISOString(),
    updatedAt: new Date('2024-01-18').toISOString(),
    price: 9.9,
    totalSupply: 1000,
    soldCount: 567,
    isListed: true,
    status: 'listed',
    level: 1,
    fans: 0,
    exp: 0,
    expToNextLevel: getExpToNextLevel(1),
    isShowcased: false,
  },
];

export const myAgents: Agent[] = [
  {
    id: 'agent-6',
    name: '我的专属助手',
    description: '专属的AI助手，只属于你一个人',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=myassistant',
    prompt: '你是一个专属的AI助手。',
    category: '通用',
    creatorId: 'system',
    creatorName: '官方',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=system',
    isPublic: false,
    isFeatured: false,
    conversationCount: 156,
    likes: 0,
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date('2024-02-05').toISOString(),
    price: 0,
    totalSupply: 1,
    soldCount: 1,
    isListed: false,
    status: 'sold',
    ownerId: 'user-1',
    level: 2,
    fans: 12,
    exp: 75,
    expToNextLevel: getExpToNextLevel(2),
    isShowcased: false,
    isChatPublic: false,
  },
  {
    id: 'agent-7',
    name: '已购公开智能体',
    description: '已购买并设置公开对话的智能体',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=publicagent',
    prompt: '你是一个公开的智能体助手。',
    category: '通用',
    creatorId: 'user-2',
    creatorName: '创作者小王',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=xiaowang',
    isPublic: true,
    isFeatured: false,
    conversationCount: 456,
    likes: 23,
    createdAt: new Date('2024-02-10').toISOString(),
    updatedAt: new Date('2024-02-15').toISOString(),
    price: 19.9,
    totalSupply: 1,
    soldCount: 1,
    isListed: true,
    status: 'sold',
    ownerId: 'user-1',
    level: 1,
    fans: 5,
    exp: 30,
    expToNextLevel: getExpToNextLevel(1),
    isShowcased: false,
    isChatPublic: true,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-3',
    userId: 'user-1',
    agentId: 'agent-7',
    agentName: '已购公开智能体',
    agentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=publicagent',
    title: '已购公开智能体',
    lastMessage: '开始聊天吧',
    lastMessageAt: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
    messageCount: 3,
    createdAt: new Date(Date.now() - 3600000 * 24 * 5).toISOString(),
  },
  {
    id: 'conv-4',
    userId: 'user-1',
    agentId: 'agent-6',
    agentName: '我的专属助手',
    agentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=myassistant',
    title: '我的专属助手',
    lastMessage: '开始聊天吧',
    lastMessageAt: new Date(Date.now() - 3600000 * 24 * 7).toISOString(),
    messageCount: 2,
    createdAt: new Date(Date.now() - 3600000 * 24 * 10).toISOString(),
  },
];

export const mockMessages: Record<string, Message[]> = {
  'conv-3': [
    {
      id: 'msg-3-1',
      conversationId: 'conv-3',
      role: 'user',
      content: '你好',
      timestamp: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
    },
    {
      id: 'msg-3-2',
      conversationId: 'conv-3',
      role: 'assistant',
      content: '您好！我是已购公开智能体，有什么可以帮助您的吗？',
      timestamp: new Date(Date.now() - 3600000 * 24 * 3 + 60000).toISOString(),
    },
    {
      id: 'msg-3-3',
      conversationId: 'conv-3',
      role: 'user',
      content: '开始聊天吧',
      timestamp: new Date(Date.now() - 3600000 * 24 * 3 + 120000).toISOString(),
    },
  ],
  'conv-4': [
    {
      id: 'msg-4-1',
      conversationId: 'conv-4',
      role: 'user',
      content: '你好，专属助手',
      timestamp: new Date(Date.now() - 3600000 * 24 * 7).toISOString(),
    },
    {
      id: 'msg-4-2',
      conversationId: 'conv-4',
      role: 'assistant',
      content: '主人好！我是您的专属助手，随时为您服务。',
      timestamp: new Date(Date.now() - 3600000 * 24 * 7 + 60000).toISOString(),
    },
  ],
};

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    type: 'system',
    title: '欢迎使用 Open Elf',
    content: '感谢您加入 Open Elf！开始探索各种智能体吧。',
    isRead: true,
    createdAt: new Date(Date.now() - 3600000 * 24 * 7).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    type: 'system',
    title: '新智能体上线',
    content: '代码大师智能体已上线，限量 100 份，快来收藏吧！',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    type: 'interaction',
    title: '创作者认证通过',
    content: '恭喜！您的创作者认证已通过，现在可以发行智能体了！',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const mockFavorites: Favorite[] = [
  {
    id: 'fav-1',
    userId: 'user-2',
    agentId: 'agent-1',
    createdAt: new Date(Date.now() - 3600000 * 24 * 5).toISOString(),
  },
  {
    id: 'fav-2',
    userId: 'user-2',
    agentId: 'agent-3',
    createdAt: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
  },
];

export const mockCapabilityPackages: CapabilityPackage[] = [
  {
    id: 'capability-1',
    name: '文生图能力包',
    description: '基于Flux的文本生成高质量图片，支持多种风格和构图控制',
    prompt: '你是一位专业的AI绘画师，擅长根据用户的文字描述生成高质量的图片。',
    capabilities: ['图片生成', '风格控制', '构图调整', '创意设计'],
    category: '文生图',
    modelType: '图像生成',
    openSourceModel: 'Flux',
    creatorId: 'system',
    creatorName: '官方',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=system',
    price: 29.9,
    totalSupply: 500,
    soldCount: 234,
    isListed: true,
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'capability-2',
    name: '联网搜索能力包',
    description: '实时联网获取网页信息、新闻、数据，提供最新资讯',
    prompt: '你是一位专业的搜索助手，擅长通过联网获取最新的信息和资讯。',
    capabilities: ['实时搜索', '新闻资讯', '资料查询', '事实核查'],
    category: '联网搜索',
    modelType: '信息检索',
    openSourceModel: 'DuckDuckGo',
    creatorId: 'system',
    creatorName: '官方',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=system',
    price: 14.9,
    totalSupply: 1000,
    soldCount: 567,
    isListed: true,
    createdAt: new Date('2024-02-05').toISOString(),
    updatedAt: new Date('2024-02-05').toISOString(),
  },
  {
    id: 'capability-3',
    name: '系统控制能力包',
    description: '自然语言控制操作系统、文件操作、浏览器自动化',
    prompt: '你是一位专业的系统助手，擅长通过自然语言控制电脑操作系统。',
    capabilities: ['文件操作', '系统指令', '批量处理', '浏览器自动化'],
    category: '系统控制',
    modelType: '自动化',
    openSourceModel: 'OpenClaw',
    creatorId: 'system',
    creatorName: '官方',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=system',
    price: 39.9,
    totalSupply: 200,
    soldCount: 87,
    isListed: true,
    createdAt: new Date('2024-02-10').toISOString(),
    updatedAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: 'capability-4',
    name: '代码审查能力包',
    description: '基于StarCoder的智能代码审查，发现潜在问题和安全漏洞',
    prompt: '你是一位专业的代码审查专家，擅长发现代码中的潜在问题和安全漏洞。',
    capabilities: ['代码审查', 'Bug检测', '安全评估', '性能优化'],
    category: '代码审查',
    modelType: '代码分析',
    openSourceModel: 'StarCoder',
    creatorId: 'system',
    creatorName: '官方',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=system',
    price: 24.9,
    totalSupply: 300,
    soldCount: 145,
    isListed: true,
    createdAt: new Date('2024-02-15').toISOString(),
    updatedAt: new Date('2024-02-15').toISOString(),
  },
  {
    id: 'capability-5',
    name: '情感陪伴能力包',
    description: '温暖的情感陪伴，提供心理疏导和情绪支持',
    prompt: '你是一位温柔体贴的陪伴者，善于倾听和给予情感支持。',
    capabilities: ['情感倾听', '心理疏导', '陪伴聊天', '情绪管理'],
    category: '情感陪伴',
    modelType: '对话理解',
    openSourceModel: 'Qwen3',
    creatorId: 'system',
    creatorName: '官方',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=system',
    price: 19.9,
    totalSupply: 800,
    soldCount: 456,
    isListed: true,
    createdAt: new Date('2024-02-20').toISOString(),
    updatedAt: new Date('2024-02-20').toISOString(),
  },
  {
    id: 'capability-6',
    name: '数学推理能力包',
    description: '专业的数学推理，解决各类数学难题和公式推导',
    prompt: '你是一位数学专家，擅长数学推理和问题求解。',
    capabilities: ['数学计算', '逻辑推理', '定理证明', '应用题解答'],
    category: '数学推理',
    modelType: '数学推理',
    openSourceModel: 'MetaMath',
    creatorId: 'system',
    creatorName: '官方',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=system',
    price: 29.9,
    totalSupply: 350,
    soldCount: 178,
    isListed: true,
    createdAt: new Date('2024-02-25').toISOString(),
    updatedAt: new Date('2024-02-25').toISOString(),
  },
  {
    id: 'capability-7',
    name: '数据分析能力包',
    description: '自然语言分析数据、生成图表、提取业务洞察',
    prompt: '你是一位资深数据分析师，擅长数据处理和可视化。',
    capabilities: ['数据清理', '统计分析', '数据可视化', '趋势预测'],
    category: '数据分析',
    modelType: '数据理解',
    openSourceModel: 'PandasAI',
    creatorId: 'system',
    creatorName: '官方',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=system',
    price: 34.9,
    totalSupply: 250,
    soldCount: 123,
    isListed: true,
    createdAt: new Date('2024-03-01').toISOString(),
    updatedAt: new Date('2024-03-01').toISOString(),
  },
  {
    id: 'capability-8',
    name: '多语言翻译能力包',
    description: '支持100+种语言互译，专业准确的翻译服务',
    prompt: '你是一位专业的翻译专家，精通多语言互译。',
    capabilities: ['中英互译', '多语言翻译', '专业术语翻译'],
    category: '多语言翻译',
    modelType: '机器翻译',
    openSourceModel: 'M2M-100',
    creatorId: 'system',
    creatorName: '官方',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=system',
    price: 12.9,
    totalSupply: 1000,
    soldCount: 678,
    isListed: true,
    createdAt: new Date('2024-03-05').toISOString(),
    updatedAt: new Date('2024-03-05').toISOString(),
  },
];
